CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    created_at TIMESTAMP NOT NULL,                          
    updated_at TIMESTAMP,                                   
    username VARCHAR(50) NOT NULL UNIQUE,              
    password VARCHAR(255) NOT NULL,                       
    email VARCHAR(255) NOT NULL UNIQUE,             
    role VARCHAR(255) NOT NULL                            
);

MERGE INTO users (username, password, email, role, created_at, updated_at) 
KEY(username) 
VALUES ('testuser', '$2a$10$NyHkZdTRUqZQwDApDx85NeNF0YWq.koidKQ1rBcI6ROU4j.zwgmly', 'existing@example.com', 'USER', '2025-04-18 16:54:10.127549', '2025-04-18 16:54:10.127549');

MERGE INTO users (username, password, email, role, created_at, updated_at) 
KEY(username) 
VALUES ('existinguser', '$2a$10$NyHkZdTRUqZQwDApDx85NeNF0YWq.koidKQ1rBcI6ROU4j.zwgmly', 'unique@example.com', 'USER', '2025-04-18 16:54:10.127549', '2025-04-18 16:54:10.127549');

MERGE INTO users (username, password, email, role, created_at, updated_at) 
KEY(username) 
VALUES ('testadmin', '$2a$10$NyHkZdTRUqZQwDApDx85NeNF0YWq.koidKQ1rBcI6ROU4j.zwgmly', 'admin@example.com', 'ADMIN', '2025-04-18 16:54:10.127549', '2025-04-18 16:54:10.127549');
