CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    created_at TIMESTAMP NOT NULL,                          
    updated_at TIMESTAMP,                                   
    username VARCHAR(50) NOT NULL UNIQUE,              
    password VARCHAR(255) NOT NULL,                       
    email VARCHAR(255) NOT NULL UNIQUE,             
    role VARCHAR(255) NOT NULL                            
);

MERGE INTO users KEY(username) VALUES ('testuser', 'aaa', 'testuser@example.com', 'ROLE_USER');

MERGE INTO users KEY(username) VALUES ('authtester', 'bbb', 'auth@example.com', 'ROLE_ADMIN');

MERGE INTO users KEY(username) VALUES ('existinguser', 'ccc', 'existing@example.com', 'ROLE_USER'); 